

services:
  postgres:
    image: postgres:latest
    container_name: kirby-store-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kirby_store
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_sql/init.sql:/docker-entrypoint-initdb.d/init.sql 
  
  

volumes:
  pgdata:  