version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.9
    steps:
      - checkout
      - aws-cli/setup

      # Install dependencies
      - run: npm ci

      # Build frontend Angular app
      - run: npm run build

      # Compile backend TypeScript
      - run: npm run build_api

      - run:
          name: Set up SSH key
          command: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan ec2-3-149-229-145.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      # Deploy frontend to S3
      - run: aws s3 sync ./dist/kirby-online-store/browser/ s3://udacity-bucket-doy

      # Deploy backend and run migrations on EC2
      - run:
          name: Deploy Backend & Migrate DB on EC2
          command: |
            if [ ! -d ./build ]; then
              echo "Error: ./build directory does not exist. Check your build process."
              exit 1
            fi

            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com << 'EOF'
              # Install dependencies
              sudo yum install -y curl postgresql
              curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
              sudo yum install -y nodejs

              # Create app directory
              mkdir -p ~/app
            EOF

            # Copy all necessary files
            scp -r ./build/* ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com:/home/ec2-user/app/
            scp ./database.json ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com:/home/ec2-user/app/
            scp -r ./migrations/ ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com:/home/ec2-user/app/
            scp ./package.json ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com:/home/ec2-user/app/

            # Run migrations and start backend with env vars
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com << 'EOF'
              cd ~/app

              # Set environment variables
              export POST_DATABASE=kirby_store
              export POST_DATABASE_TEST=kirby_store_test
              export POST_HOST=127.0.0.1
              export POST_USER=postgres
              export POST_PASSWORD=postgres
              export ENV=build
              export BCRPYT=Kirbys-Dream-Land
              export SALT_RROUNDS=19
              export TOKEN_SECRET=poyo

              # Install and run
              npm install
              npm run migrate-up
              nohup npm run start_api &
            EOF

workflows:
  build-deploy:
    jobs:
      - build-and-deploy
