version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:20.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build frontend
          command: |
            npm ci
            npm run build || (echo "\n==== Build failed: Clearing node_modules and reinstalling dependencies ====" && rm -rf node_modules package-lock.json && npm ci && npm run build)
      - run:
          name: Compile backend
          command: npm run tsc
      - run:
          name: Deploy frontend to S3
          command: aws s3 sync ./dist/kirby-online-store/ s3://udacity-bucket-doy
      - run:
          name: Deploy Backend & Migrate DB on EC2
          command: |
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com bash -c "'mkdir -p ~/app'"
            scp -r ./build/backend/* ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com:/home/ec2-user/app/
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-149-229-145.us-east-2.compute.amazonaws.com bash -c "'cd ~/app && npm install && npm run migrate-up && nohup npm run start_api &'"

workflows:
  build-deploy:
    jobs:
      - build-and-deploy
